#配置文件,修改配置后重启Bot生效!!!
#必填项!
##1.api的IP,不了解就保持默认
api_ip:
  - '91.217.139.190:5010' #备用服务器
  - '91.216.169.75:5010' #主服务器
  - '185.80.202.180:5010' #备用服务器2

sd_api_ip: "http://{ip}/sdapi/v1/img2img" #sdui的api地址,用来以图绘图
##2.访问上述ip/token 获取
token:
  - ''

##3. 默认绘图参数
tags_moren: "miku" #默认的tags
ntags_moren: "lowres, badanatomy, bad hands, text, error, missing fingers, extradigit, fewerdigits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark,username,blurry" #默认的负面tags
ntags_safe: "nsfw, nude" #默认的防止漏点的ntags,清空则无效
scale_moren: 11 #默认的scale
shape_moren: "Portrait" #形状参数
strength_moren: "0.60" #以图绘图原图关联,越低越关联
r18_moren: 0 #默认是否开启r18,1为开启
##4. 绘图超时时间，单位秒
draw_timeout: 180
##5. 元素法典相似度,高于该值的魔咒会被覆盖
max_ratio: 0.8

#可选项!
#整理tags功能
arrange_tags: True
#数据库相关功能
##1. 是否开启数据录入
add_db: True
##2. 用于查看图片时，每页最多有多少张图
per_page_num: 32
#翻译功能
##1. 是否开启翻译
trans: True
##2. 翻译方式(0为有道,1为百度),api地址,应用id,应用密钥
way2trans: 0
youdao_url: "https://openapi.youdao.com/api"
youdao_app_id: ""
youdao_app_key: ""

baidu_url: "http://api.fanyi.baidu.com/api/trans/vip/translate"
baidu_app_id: ""
baidu_app_key: ""
#过滤功能
##1. 是否开启违禁词过滤
limit_word: True
##2. 违禁词表,字典树的方式,如 naked 会过滤掉 "nakedasdasda" 里的 "naked" 剩下 "dasdasda"
wordlist: ['&r18=1', 'nake', 'vagina', 'penis', 'nsfw', 'genital', 'nude', 'nipple', 'vulv', 'no pant', 'clothes remove', 'rectum','%']



#鉴赏图片功能
img2tag: True #是否开启
img2tags_url: "https://hf.space/embed/NoCrypt/DeepDanbooru_string" #有排队功能的DeepDanbooru仓库,默认及格式: https://hf.space/embed/hysts/DeepDanbooru(用这个得改一改) 即https://hf.space/embed/{ID}/{仓库名}
img2tags_url_timeout: 30 #请求超时时间

#图片动漫化功能
img2anime: False #是否开启
img2anime_url: "" #有排队功能的White-box-Cartoonization仓库,默认及格式: https://hf.space/embed/hylee/White-box-Cartoonization
img2anime_url_timeout: 120

#超分图片功能
picsuper: False #是否开启
pic_super_url: "" #有排队功能的Real-CUGAN仓库,无默认,格式: https://hf.space/embed/{XXXXX}/Real-CUGAN 或其它
max_size: 11664000 #超分图片的最大尺寸为1080*1080,过大有风险
pic_super_timeout: 120


#PS 以超分图片为例
#如果你是混乱邪恶阵营前往https://huggingface.co/spaces?search=real-cugan  ,然后点进去，然后复制SPACE的名称如saber2022/Real-CUGAN 这样的东西，注意需要仓库开启排队的功能，如果原有仓库无排队功能前往链接：https://pan.baidu.com/s/1BgD_WaBBkBn5Rrt9TNt0Zw?pwd=2333 获取文件然后上传至仓库